version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/html
      - ./node_modules/.cache/.eslintcache:/var/www/html/node_modules/.cache/.eslintcache
    command: >
      sh -c "npm start"
